application:
  subdomain: smarticky
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://smarticky:8080/
  injects:
    - id: login-autofill
      when:
        - /login
      do:
        - src: builtin://simple-inject-password
          params:
            user: "{{.U.admin_username}}"
            password: "{{.U.admin_password}}"
    - id: open-save-chooser
      on: browser
      when:
        - "/*"
      do:
        - src: file:///lzcapp/pkg/content/lazycat-injects/lzc-file-chooser-inject.js

services:
  smarticky:
    # czyt/smarticky:v0.4.0
    image: registry.lazycat.cloud/czyt/czyt/smarticky:fe5eaa46cc9f32b4
    binds:
      - /lzcapp/var/data:/data
    environment:
      - SMARTICKY_DATA_DIR=/data
      - PORT=8080
      - SMARTICKY_ADMIN_USERNAME={{.U.admin_username}}
      - SMARTICKY_ADMIN_PASSWORD={{.U.admin_password}}
      - SMARTICKY_ADMIN_EMAIL={{.U.admin_email}}
      - SMARTICKY_ADMIN_NICKNAME={{.U.admin_nickname}}
      - SMARTICKY_TRUST_LAZYCAT_HEADERS=true
