application:
  subdomain: smarticky
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://smarticky:8080/
  injects:
    - id: open-save-chooser
      on: browser
      when:
        - "/*"
      do:
        - src: file:///lzcapp/pkg/content/lazycat-injects/lzc-file-chooser-inject.js

services:
  smarticky:
    # czyt/smarticky:v0.3.0
    image: registry.lazycat.cloud/czyt/czyt/smarticky:244cd879d2a552be
    binds:
      - /lzcapp/var/data:/data
    environment:
      - SMARTICKY_DATA_DIR=/data
      - PORT=8080
